# Generated by Django 5.2.7 on 2025-10-28 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage', '0002_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitragemCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_a', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor A (R$):')),
                ('cripto_a', models.CharField(max_length=200, verbose_name='Cripto A:')),
                ('price_b', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor B (R$):')),
                ('cripto_b', models.CharField(max_length=200, verbose_name='Cripto B:')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data:')),
                ('processo', models.CharField(max_length=200, verbose_name='Processo:')),
            ],
        ),
    ]
