# Generated by Django 5.2.7 on 2025-10-29 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage', '0003_arbitragemcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 3, 20, 27, 232198), verbose_name='Data:'),
        ),
        migrations.AlterField(
            model_name='arbitragemcard',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 3, 20, 27, 232897), verbose_name='Data:'),
        ),
    ]
