# Generated by Django 5.2.7 on 2025-10-29 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage', '0006_alter_arbitragem_data_alter_arbitragemcard_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 4, 16, 59, 51029), verbose_name='Data:'),
        ),
        migrations.AlterField(
            model_name='arbitragemcard',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 4, 16, 59, 51742), verbose_name='Data:'),
        ),
    ]
