# Generated by Django 5.2.7 on 2025-10-29 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage', '0009_alter_arbitragem_data_alter_arbitragemcard_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 11, 17, 57, 174168), verbose_name='Data:'),
        ),
        migrations.AlterField(
            model_name='arbitragemcard',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 11, 17, 57, 174873), verbose_name='Data:'),
        ),
    ]
