# Generated by Django 5.2.7 on 2025-10-29 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage', '0012_alter_arbitragem_data_alter_arbitragemcard_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 12, 42, 11, 774223), verbose_name='Data:'),
        ),
        migrations.AlterField(
            model_name='arbitragemcard',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 12, 42, 11, 774960), verbose_name='Data:'),
        ),
    ]
