# Generated by Django 5.2.7 on 2025-10-29 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage', '0013_alter_arbitragem_data_alter_arbitragemcard_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitragem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 13, 30, 55, 281082), verbose_name='Data:'),
        ),
        migrations.AlterField(
            model_name='arbitragemcard',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 13, 30, 55, 282204), verbose_name='Data:'),
        ),
    ]
