# Generated by Django 5.2.7 on 2025-10-30 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arbitrage', '0015_alter_arbitragem_data_alter_arbitragemcard_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
