# Generated by Django 5.2.7 on 2025-10-29 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moedas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=200, verbose_name='Símbolo:')),
                ('name', models.CharField(max_length=200, verbose_name='Nome:')),
                ('platforms', models.CharField(max_length=200, verbose_name='Plataforma:')),
                ('currency', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor:')),
                ('data', models.DateTimeField(default=datetime.datetime(2025, 10, 29, 4, 0, 20, 787673), verbose_name='Data:')),
            ],
        ),
    ]
