# Generated by Django 5.2.7 on 2025-10-29 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moedas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 4, 16, 59, 53094), verbose_name='Data:'),
        ),
    ]
