# Generated by Django 5.2.7 on 2025-10-29 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_alter_moedas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moedas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 10, 3, 5, 992954), verbose_name='Data:'),
        ),
    ]
