# Generated by Django 5.2.7 on 2025-10-29 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_alter_moedas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moedas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 11, 17, 57, 176304), verbose_name='Data:'),
        ),
    ]
