# Generated by Django 5.2.7 on 2025-10-29 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0007_alter_moedas_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoedasADM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('name', models.CharField(max_length=200, verbose_name='Nome:')),
            ],
        ),
        migrations.AlterField(
            model_name='moedas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 12, 42, 11, 776715), verbose_name='Data:'),
        ),
    ]
