# Generated by Django 5.2.7 on 2025-10-29 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0009_alter_moedas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moedas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 29, 13, 33, 7, 127932), verbose_name='Data:'),
        ),
    ]
