# Generated by Django 5.2.7 on 2025-10-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0012_alter_moedas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moedas',
            name='data',
            field=models.DateTimeField(verbose_name='Data:'),
        ),
    ]
