# Generated by Django 5.2.7 on 2025-10-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0013_alter_moedas_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moedas',
            name='symbol',
            field=models.TextField(max_length=200, verbose_name='Símbolo:'),
        ),
    ]
