# Generated by Django 5.2.7 on 2025-10-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0014_alter_moedas_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='moedas',
            name='idn',
            field=models.CharField(default=None, max_length=200, verbose_name='Idn:'),
            preserve_default=False,
        ),
    ]
