# Generated by Django 5.2.7 on 2025-11-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0016_alter_moedas_platforms'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoedasImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idn', models.CharField(max_length=200, verbose_name='Idn:')),
                ('symbol', models.TextField(max_length=200, verbose_name='Símbolo:')),
                ('name', models.CharField(max_length=200, verbose_name='Nome:')),
                ('platforms', models.TextField(max_length=200, verbose_name='Plataforma:')),
                ('currency', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor:')),
            ],
        ),
    ]
