# Generated by Django 5.2.7 on 2025-11-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0017_moedasimport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MoedasImport',
        ),
    ]
