# Generated by Django 5.2.7 on 2025-11-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0018_delete_moedasimport'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroProgresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
