# Generated by Django 5.2.7 on 2025-11-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0019_registroprogresso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistroProgresso',
        ),
    ]
