# Generated by Django 5.2.7 on 2025-11-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0020_delete_registroprogresso'),
    ]

    operations = [
        migrations.AddField(
            model_name='moedasadm',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='I', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='moedas',
            name='currency',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='moedas',
            name='data',
            field=models.DateTimeField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='moedas',
            name='idn',
            field=models.CharField(max_length=200, verbose_name='Idn'),
        ),
        migrations.AlterField(
            model_name='moedas',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='moedas',
            name='platforms',
            field=models.TextField(max_length=200, verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='moedas',
            name='symbol',
            field=models.TextField(max_length=200, verbose_name='Simbolo'),
        ),
        migrations.AlterField(
            model_name='moedasadm',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
    ]
