# Generated by Django 5.2.7 on 2025-11-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0021_moedasadm_status_alter_moedas_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moedasadm',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
